services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: local
    volumes:
      - postgres_data:/var/lib/postgresql/data

  migrator:
    build:
      context: .
    command: npm run db:push
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://admin:admin@db:5432/local

  web:
    build:
      context: .
    ports:
      - "3000:3000"
    depends_on:
      - migrator
    environment:
      DATABASE_URL: postgres://admin:admin@db:5432/local
    restart: always

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
    restart: always

volumes:
  postgres_data:
